config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  get 'main/index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :operations
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category
  validates :amount, presence: true, numericality: {greater_than: 0}
  validates :operation_date, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:amount, :operation_date, :description, :category_id)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def report_by_category
    @operations = Operation.group(:name)
  end

  def report_by_dates
    start_date = params[:start_date]
    end_date = params[:end_date]
    @operations = Operation.select{ |date| date >= start_date && date <= end_date}
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceAppBoiko</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :operation_date, style: "display: block" %>
    <%= form.datetime_field :operation_date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <p>
    <strong>Amount:</strong>
    <%= operation.amount %>
  </p>

  <p>
    <strong>Operation date:</strong>
    <%= operation.operation_date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= operation.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= operation.category_id %>
  </p>

</div>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Show this operation", @operation %> |
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Operations</h1>

<div id="operations">
  <% @operations.each do |operation| %>
    <%= render operation %>
    <p>
      <%= link_to "Show this operation", operation %>
    </p>
  <% end %>
</div>

<%= link_to "New operation", new_operation_path %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render "form", operation: @operation %>

<br>

<div>
  <%= link_to "Back to operations", operations_path %>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @operation %>

<div>
  <%= link_to "Edit this operation", edit_operation_path(@operation) %> |
  <%= link_to "Back to operations", operations_path %>

  <%= button_to "Destroy this operation", @operation, method: :delete %>
</div>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

<%# <a href="/reports/report_by_category"><button type="button">Графік</button><a>
<a href="/reports/report_by_dates"><button type="button">По датам</button></a> %>


<form>
    Початок періоду: <input name="start_date" type="date"><br>
    Кінець періоду: <input name="end_date" type="date"><br>
    Тип операцій:
    Категорія: 


    <button type="submit" formaction="/reports/report_by_category">Графік</button>
    <button type="submit" formaction="/reports/report_by_dates">По датам</button>
</form>

app/views/reports/report_by_category.html.erb
<h1>Reports#report_by_category</h1>
<p>Find me in app/views/reports/report_by_category.html.erb</p>






<ol>
<%sum=0%>
<% @operations.each do |operation|%>
    <%sum+=operation.amount%>
    <li><%= operation.category.name%>, <%= operation.amount%>, <%= operation.description%></li>
     <%end%>
    <p>Total <%=sum%></p>
</ol>

app/views/reports/report_by_dates.html.erb
<h1>Reports#report_by_dates</h1>
<p>Find me in app/views/reports/report_by_dates.html.erb</p>



<ol>
<%sum=0%>
<% @operations.each do |operation|%>
    <%sum+=operation.amount%>
    <li><%= operation.category.name%>, <%= operation.amount%>, <%= operation.description%></li>
     <%end%>
    <p>Total <%=sum%></p>
</ol>